service: test-serverless-packaging

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  timeout: 10
  versionFunctions: false
  tracing:
    lambda: true

functions:
  hello:
    handler: index.handler
    name: test-serverless-packaging-lambda